version: "3.8"

services:

  ToughLove_Main:
    image: yaoyingsmu/toughlove_main:latest
    build:
      context: .
      dockerfile: dockerfiles/main.dockerfile
    # restart: always
    container_name: ToughLove_Main
    ports:
      - "5000:5000"

  # ToughLove_Test:
  #     image: yaoyingsmu/toughlove_test:latest
  #     build:
  #         context: .
  #         dockerfile: dockerfiles/test.dockerfile
  #     # restart: always
  #     container_name: ToughLove_Test
  #     ports:
  #         - "5001:5001"
  #     depends_on:
  #         - ToughLove_Main

  ToughLove_Social:
    image: yaoyingsmu/toughlove_social:latest
    build:
      context: .
      dockerfile: dockerfiles/social.dockerfile
    container_name: ToughLove_Social
    ports:
      - "5001:5001"
    depends_on:
      - ToughLove_Main

  ToughLove_Intent:
    image: yaoyingsmu/toughlove_intent:latest
    build:
      context: .
      dockerfile: dockerfiles/intent.dockerfile
    container_name: ToughLove_Intent
    ports:
      - "5002:5002"
    depends_on:
      - ToughLove_Main

  ToughLove_Insult:
    image: yaoyingsmu/toughlove_insult:latest
    build:
      context: .
      dockerfile: dockerfiles/insult.dockerfile
    container_name: ToughLove_Insult
    ports:
      - "5003:5003"
    depends_on:
      - ToughLove_Main
