version: "3.8"

services:
    
    # ATLAS_Orchestrator:
    #     image: yaoyingsmu/atlas_orchestrator:latest
    #     build: 
    #         context: .
    #         dockerfile: dockerfiles/ATLAS_Orchestrator.Dockerfile
    #     restart: always
    #     container_name: ATLAS_Orchestrator
    #     ports:
    #         - "5000:5000"

    socialChatbot:
        image: yaoyingsmu/social_chatbot:latest
        build:
            context: .
            dockerfile: dockerfiles/social.Dockerfile
        restart: always
        container_name: SocialChatbot
        ports:
            - "5001:5001"
        # depends_on:
        #     - ATLAS_Orchestrator